-- ============================================================
-- CampusQueue_System — database schema (v5, matches live demo)
-- ============================================================
-- Updates in this version vs. v4:
--   1. username = student_number for every student account,
--      enforced with chk_student_username_is_student_number.
--      Students no longer pick their own username at all.
--   2. Re-added chk_student_email_format (studentnumber@mywsu.ac.za),
--      confirmed present in this version — see the note in the users
--      table for why the CHECK is a backstop, not the primary guarantee.
--
-- Carried over from v4:
--   1. queue_tickets.notified_tier — persists which proximity-
--      notification tier (#1/#2/#3, see README.md) a waiting ticket
--      has already been sent, so it fires exactly once per tier.
--
-- Carried over from v3:
--   1. The session-assignment model: service_points are fixed
--      desk→queue mappings; queues.current_admin_id tracks who is
--      managing a queue THIS session, set at login and cleared at
--      logout/"Switch Queue".
--   2. Ticket status renamed: 'serving'→'called', 'completed'→'served'.
--   3. The service_points table (counters/desks).
--   4. The Student Card service/queue (Campus Control, near the
--      Music Department).
--   5. Passwords are hashed; login is by username, not email.
--   6. Ticket numbers are generated atomically (queue_counters +
--     a UNIQUE constraint).
--   7. Ticket "position" is NOT stored — calculated on read.
--   8. Queue status includes 'paused'; ticket status includes
--     'skipped', distinct from 'cancelled'.
--   9. admin_actions.admin_id uses ON DELETE SET NULL.


CREATE DATABASE IF NOT EXISTS CampusQueue_System
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE CampusQueue_System;


-- USERS

CREATE TABLE users (
    user_id         INT AUTO_INCREMENT PRIMARY KEY,
    full_name       VARCHAR(100) NOT NULL,
    username        VARCHAR(50) NOT NULL UNIQUE,   -- for students: always equals student_number
                                                     -- (see CHECK constraint below) — not a separate
                                                     -- value the student picks
    student_number  VARCHAR(20) UNIQUE,            -- NULL for admin/staff accounts
    email           VARCHAR(100) NOT NULL UNIQUE,  -- for students: always studentnumber@mywsu.ac.za,
                                                     -- generated by the backend, never typed by hand
    password_hash   VARCHAR(255) NOT NULL,         -- hashed, never plaintext
    role            ENUM('student', 'admin') NOT NULL DEFAULT 'student',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_student_email_format CHECK (
        role <> 'student' OR email REGEXP '^[0-9]+@mywsu\\.ac\\.za$'
    ),
    CONSTRAINT chk_student_username_is_student_number CHECK (
        role <> 'student' OR username = student_number
    )
    -- Both CHECKs are skipped whenever role <> 'student' (admin/staff
    -- accounts use their own email domain and choose their own username).
) ENGINE=InnoDB;


-- SERVICES  (a campus department/service, e.g. "Financial Aid")

CREATE TABLE services (
    service_id      INT AUTO_INCREMENT PRIMARY KEY,
    service_name    VARCHAR(100) NOT NULL,
    description     TEXT,
    location        VARCHAR(150)
) ENGINE=InnoDB;


-- QUEUES  (one or more queues can belong to a single service)

CREATE TABLE queues (
    queue_id          INT AUTO_INCREMENT PRIMARY KEY,
    service_id        INT NOT NULL,
    queue_name        VARCHAR(100) NOT NULL,
    prefix            VARCHAR(5) NOT NULL UNIQUE,    -- needed to build ticket numbers, e.g. "REG"
    status            ENUM('open', 'paused', 'closed') NOT NULL DEFAULT 'open',
    current_admin_id  INT NULL,                      -- CHANGED: moved here from service_points.
                                                        -- This is the "who is managing this queue
                                                        -- THIS SESSION" field — set when an admin
                                                        -- picks "today's service/queue" at login,
                                                        -- cleared on logout or "Switch Queue".
                                                        -- It belongs on the queue, not the desk,
                                                        -- because the desk (service_point) a queue
                                                        -- is served from is fixed; it's the admin
                                                        -- working that queue who rotates.
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (service_id) REFERENCES services(service_id)
        ON DELETE RESTRICT,  -- prevents accidentally wiping out queues (and
                              -- their ticket history) just by deleting the
                              -- parent service. Delete queues explicitly
                              -- first if a service is retired.
    FOREIGN KEY (current_admin_id) REFERENCES users(user_id)
        ON DELETE SET NULL   -- if that admin's account is ever deleted, the
                              -- queue simply becomes unmanaged, not orphaned
) ENGINE=InnoDB;


-- QUEUE_COUNTERS  (enables atomic, race-condition-free
-- ticket number generation, one row per queue)

CREATE TABLE queue_counters (
    queue_id        INT PRIMARY KEY,
    last_number     INT NOT NULL DEFAULT 0,
    FOREIGN KEY (queue_id) REFERENCES queues(queue_id)
        ON DELETE CASCADE
) ENGINE=InnoDB;


-- QUEUE_TICKETS

CREATE TABLE queue_tickets (
    ticket_id        INT AUTO_INCREMENT PRIMARY KEY,
    user_id          INT NOT NULL,
    queue_id         INT NOT NULL,
    sequence_number  INT NOT NULL,                -- raw number, locked/incremented atomically
    ticket_number    VARCHAR(20) NOT NULL,         -- formatted, e.g. "REG-3" (prefix + sequence_number)
    status           ENUM('waiting', 'called', 'served', 'skipped', 'cancelled')
                     DEFAULT 'waiting',            -- RENAMED: 'serving'→'called', 'completed'→'served'
                                                     -- to match the frontend's Call Next / Mark Served actions
    notified_tier    TINYINT NOT NULL DEFAULT 0,   -- NEW: which proximity tier (1, 2, or 3) this
                                                     -- ticket has already been notified for, so the
                                                     -- tiered notification (see README.md) fires once
                                                     -- per tier and never repeats — persisted here
                                                     -- rather than kept in memory, since the app may
                                                     -- restart or run multiple instances
    joined_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    called_at        TIMESTAMP NULL,
    served_at        TIMESTAMP NULL,                -- also used as "resolved at" when status = 'skipped'
    FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE,
    FOREIGN KEY (queue_id) REFERENCES queues(queue_id)
        ON DELETE CASCADE,
    UNIQUE KEY uq_queue_sequence (queue_id, sequence_number)  -- DB-level safety
        -- net; even if application code has a bug, MySQL itself rejects a
        -- duplicate ticket number within the same queue.
) ENGINE=InnoDB;

-- NOTE: there is deliberately no "position" column here. A stored
-- position value goes stale the instant any ticket ahead of it changes
-- status, unless you add triggers to recalculate the entire queue on
-- every single serve/skip/cancel. Instead, calculate position on read.
-- See README.md for the exact query.


-- SERVICE_POINTS  (physical counters/desks. Each one is fixed
-- to a single queue permanently — Counter 1 is always the
-- Registration desk. See the design note below for what DOES
-- change per session: which admin is managing that queue.
-- Placed after queue_tickets since current_ticket_id references it.)

CREATE TABLE service_points (
    service_point_id  INT AUTO_INCREMENT PRIMARY KEY,
    point_name         VARCHAR(100) NOT NULL,       -- e.g. "Counter 1"
    queue_id           INT NULL,                    -- the queue this desk
                                                      -- permanently serves — a
                                                      -- structural fact about the
                                                      -- physical location, not
                                                      -- something reassigned per
                                                      -- session
    current_ticket_id  INT NULL,                    -- the ticket currently called
                                                      -- at this counter, if any
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (queue_id) REFERENCES queues(queue_id)
        ON DELETE SET NULL,   -- deleting a queue frees up the counter rather
                               -- than deleting the counter itself
    FOREIGN KEY (current_ticket_id) REFERENCES queue_tickets(ticket_id)
        ON DELETE SET NULL
) ENGINE=InnoDB;


-- NOTIFICATIONS

CREATE TABLE notifications (
    notification_id  INT AUTO_INCREMENT PRIMARY KEY,
    user_id          INT NOT NULL,
    ticket_id        INT NULL,                    -- links a notification back to
                                                     -- the ticket it's about
    message          TEXT NOT NULL,
    status           ENUM('unread', 'read') DEFAULT 'unread',
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
        ON DELETE CASCADE,
    FOREIGN KEY (ticket_id) REFERENCES queue_tickets(ticket_id)
        ON DELETE SET NULL
) ENGINE=InnoDB;


-- ADMIN_ACTIONS  (audit log — this is what makes the
-- "admin selects today's queue" model auditable: every time an
-- admin picks a queue, calls next, serves, skips, pauses, or
-- closes, it's logged here with a timestamp and who did it.)

CREATE TABLE admin_actions (
    action_id           INT AUTO_INCREMENT PRIMARY KEY,
    admin_id            INT NULL,                 -- nullable so the log survives
                                                     -- admin account deletion
    action_description  TEXT NOT NULL,
    action_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES users(user_id)
        ON DELETE SET NULL   -- an audit trail should never disappear just
                              -- because the actor's account was later deleted
) ENGINE=InnoDB;


-- Session-based queue assignment (design note, not a table)

-- There is intentionally no "assigned_queue_id" column locking an
-- admin to one queue permanently. Instead, queues.current_admin_id
-- is UPDATEd each time a staff member logs in and picks "today's
-- service/queue" — matching real university staffing, where the
-- same person might cover Registration one day and Financial Aid
-- the next. service_points, in contrast, ARE fixed: Counter 1 is
-- always the Registration desk, permanently — it's the admin
-- working a queue that rotates, not which physical desk serves it.
--
-- Application-level flow at admin login:
--   1. Admin logs in, sees a list of queues to choose from
--      ("Which service are you managing today?").
--   2. Admin picks one for this session.
--   3. Backend runs:
--        UPDATE queues
--        SET current_admin_id = :this_admin_id
--        WHERE queue_id = :chosen_queue_id;
--   4. Backend logs it:
--        INSERT INTO admin_actions (admin_id, action_description)
--        VALUES (:this_admin_id, 'Selected Financial Aid queue for this session');
--   5. The frontend resolves which desk to show Call Next on by
--      looking up the service_point whose queue_id matches the
--      chosen queue (fixed mapping, no lookup logic needed on write):
--        SELECT * FROM service_points WHERE queue_id = :chosen_queue_id;
--
-- On logout or "Switch Queue", current_admin_id is cleared:
--        UPDATE queues SET current_admin_id = NULL WHERE queue_id = :queue_id;
--
-- This keeps per-person accountability (every action is still tied
-- to a real, individual admin account — never a shared login) while
-- staying flexible about who works which queue on a given day